services:
  db:
    image: mysql:8.0.35
    container_name: catalogue-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: catalogue_db
      MYSQL_USER: cataloguser
      MYSQL_PASSWORD: userpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    labels:
      com.docker.compose.project: "catalogue-app"
      com.docker.compose.service: "database"
      org.opencontainers.image.source: "https://hub.docker.com/_/mysql"
      org.opencontainers.image.description: "Official MySQL database for Catalogue App"
      org.opencontainers.image.version: "8.0.35"

  server:
    image: ghcr.io/santrainalex/ci_docker-compose/server:latest
    container_name: catalogue-server
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: cataloguser
      DB_PASSWORD: userpass
      DB_NAME: catalogue_db
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    image: ghcr.io/santrainalex/ci_docker-compose/client:latest
    container_name: catalogue-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

volumes:
  db_data: