name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  OWNER: santrainalex
  REPO: ci_docker-compose

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Server image
        uses: docker/build-push-action@v5
        with:
          context: ./catalogue-app/server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/server:latest

      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: ./catalogue-app/client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/client:latest
